#!/bin/sh

mysqld_safe &

mysql_ready() {
	mysqladmin ping --host=127.0.0.1 --user=root --password=root > /dev/null 2>&1
}

while !(mysql_ready)
do
	echo "waiting for mysql ..."
	sleep 3
done

php-fpm &

nginx &

tail -F /dev/null
